"use client";

import { useState } from "react";

const lessons = [
  { image: "/assets/consejo-sonrie.jpg", title: "Siempre sonríe", text: "El mundo cambia cuando lo miras con una sonrisa. Sonreír libera hormonas que te hacen sentir mejor, reduce el estrés y te conecta con los demás. Incluso en los momentos difíciles, una sonrisa puede ser el primer paso para encontrar una nueva oportunidad." },
  { image: "/assets/consejo-valentia.jpg", title: "Valentía", text: "La diferencia entre quienes se atreven y quienes no, está en la decisión de actuar a pesar del miedo. La valentía no significa no sentir miedo, sino avanzar igual. Esa pequeña acción te saca de tu zona de confort y te acerca a la vida que quieres." },
  { image: "/assets/consejo-mente.jpg", title: "Gánale a tu mente", text: "Nuestros pensamientos tienen un gran poder. Aprender a manejarlos te permite enfrentar los desafíos con una perspectiva más positiva y realista. Cuando entrenas tu mente, ganas claridad, confianza y el control para construir la vida que deseas." },
];
const experiences = [
  { image: "/assets/experiencia-se-puede.jpg", icon: "/assets/iconos-17.png", number: "01", title: "Se puede", text: "Siempre hay una manera de avanzar, descubrir tu propósito y encontrar esa luz que llevas dentro. En mi vida, muchas personas me han demostrado que los límites existen solo si nosotros los aceptamos.", callout: "DESCUBRE\nTU POTENCIAL" },
  { image: "/assets/experiencia-entrega.jpg", icon: "/assets/iconos-18.png", number: "02", title: "Entrega", text: "Que potente esta palabra si la usamos para la sociedad. Uno puede transformar e impactar muchas vidas con una acción sencilla, en beneficio de otros. Para mí es mágica la sensación de entregar tu tiempo y experiencia, y ver cómo eso también transforma tu propia vida.", callout: "IMPACTA\nA OTROS" },
  { image: "/assets/experiencia-sello.jpg", icon: "/assets/iconos-19.png", number: "03", title: "Sello", text: "Siempre he sentido una gran atracción hacia esta palabra, de impactar y generar un cambio en otros desde mi persona. Creo que cada persona en este mundo tiene una marca única que influye y deja huella. Desde mí, busco llegar a los demás con mi mensaje.", callout: "DEJA UNA\nHUELLA POSITIVA" },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main>
    <header className="site-header">
      <a href="#inicio" className="brand"><img src="/assets/logo-enzo.png" alt="Enzo Amadei" /></a>
      <nav className={menuOpen ? "nav open" : "nav"}>
        <a href="#historia" onClick={() => setMenuOpen(false)}>Acerca de mí</a><a href="#aprendizajes" onClick={() => setMenuOpen(false)}>Libérate</a><a href="#experiencias" onClick={() => setMenuOpen(false)}>Programas</a><a href="#decision" onClick={() => setMenuOpen(false)}>Charlas motivacionales</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a>
      </nav>
      <a href="#contacto" className="header-cta">Agenda una conversación <span>→</span></a><button className="menu-button" aria-label="Abrir menú" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? "×" : "☰"}</button>
    </header>

    <section id="inicio" className="hero"><img src="/assets/HERO.jpg" alt="Enzo Amadei en una conferencia" className="hero-bg" /><div className="hero-content"><p className="eyebrow light">COACH DE VIDA · CONFERENCISTA</p><h1>“Haz de tu pasado<br />una <em>historia increíble</em>”</h1><p className="hero-copy">Acompaño a personas a transformar sus experiencias en aprendizaje, recuperar su poder y crear una vida con propósito.</p><div className="button-row"><a className="button yellow" href="#experiencias">Conoce mis programas <span>→</span></a><a className="button ghost" href="#historia"><span className="play">▶</span> Ver video</a></div><div className="hero-stats"><Stat icon="/assets/icono-hero-1.png" label="PERSONAS" sub="MÁS LIBRES" /><Stat icon="/assets/icono-hero-2.png" label="VIDAS CON" sub="MÁS PROPÓSITO" /><Stat icon="/assets/icono-hero-3.png" label="HISTORIAS" sub="REALES" /></div></div><div className="hero-tag">TRANSFORMA<br />· INSPIRA ·<br />LIBÉRATE</div></section>

    <section id="historia" className="story section-image section-two"><img src="/assets/seccion-2.jpg" alt="Enzo hablando ante una audiencia" className="section-bg" /><div className="story-copy content-width"><p className="eyebrow">MI HISTORIA</p><h2>De la adversidad<br />a una vida con<br /><em>propósito</em></h2><p>Conoce mi historia y cómo transformé las dificultades en una fuente de aprendizaje para vivir con más libertad, ilusión y propósito.</p><div className="mini-lessons"><Mini icon="/assets/iconos-11.png" text="Superar desafíos" /><Mini icon="/assets/iconos-12.png" text="Recuperar la ilusión" /><Mini icon="/assets/iconos-13.png" text="Inspirar a otros" /></div><a className="button yellow" href="https://www.youtube.com/watch?v=Y55BYQF1Uyw" target="_blank" rel="noreferrer"><span className="play dark">▶</span> Ver mi historia</a></div><div className="story-video"><iframe src="https://www.youtube.com/embed/Y55BYQF1Uyw?rel=0" title="Historia de Enzo Amadei" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="quote">“La vida siempre te da<br />una nueva oportunidad”<small>Enzo Amadei</small></div></section>

    <section id="aprendizajes" className="lessons section-image"><img src="/assets/seccion-3.jpg" alt="Enzo en una conferencia" className="section-bg" /><div className="content-width centered"><p className="eyebrow">EXPERIENCIAS QUE TRANSFORMAN</p><h2>Algunos <em>consejos</em> de mi persona</h2><p className="section-intro">Reflexiones que nacen de mi experiencia y que pueden ayudarte en tu propio camino.</p><div className="lesson-grid">{lessons.map((item) => <article className="lesson-card" key={item.title}><img src={item.image} alt="" /><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

    <section id="experiencias" className="experiences section-image"><img src="/assets/seccion-4.jpg" alt="Montañas en niebla" className="section-bg" /><div className="content-width centered"><p className="eyebrow">MI CAMINO EN ACCIÓN</p><h2>Experiencias que <em>dejan huella</em></h2><p className="section-intro">Tres momentos que han marcado mi camino y que hoy quiero compartir contigo.</p><div className="experience-grid">{experiences.map((item) => <article className="experience-card" key={item.number}><img className="experience-image" src={item.image} alt="" /><div className="experience-body"><h3>{item.title}</h3><p>{item.text}</p><div className="experience-callout"><img src={item.icon} alt="" /><span>{item.callout.split("\\n").map((line) => <span key={line}>{line}</span>)}</span></div></div></article>)}</div></div></section>

    <section id="decision" className="decision section-image"><img src="/assets/seccion-5.jpg" alt="Persona subiendo una montaña" className="section-bg" /><div className="decision-copy content-width"><p className="eyebrow">CONSTRUYE TU PRESENTE</p><h2>Decisión<span>.</span></h2><p className="lead">La decisión que tomas hoy puede cambiar tu vida mañana.</p><p>Es nuestra manera de construir nuestro presente y futuro, teniendo tanto de poder esta palabra que cambia y transforma vidas dependiendo de cuál decisión tomemos.</p><div className="decision-points"><Mini icon="/assets/iconos-17.png" text="Más claridad" /><Mini icon="/assets/iconos-18.png" text="Más propósito" /><Mini icon="/assets/iconos-19.png" text="Más impacto" /></div></div></section>

    <section className="final-cta section-image"><img src="/assets/seccion-6.jpg" alt="Enzo celebrando en la montaña" className="section-bg" /><div className="final-copy content-width"><p className="eyebrow light">PERSONAS MÁS LIBRES</p><h2>No decidí mi discapacidad,<br /><em>pero sí decidí cómo vivirla.</em></h2><p>La vida siempre te va a poner desafíos, pero la decisión de cómo enfrentarlos siempre será tuya.</p><a className="button yellow" href="#contacto">¿Qué harías tú? <span>→</span></a></div><div className="final-quote">“Solo tú puedes <em>cambiar tu mundo</em>”</div></section>

    <footer id="contacto" className="footer"><div className="footer-main"><div className="footer-brand"><img src="/assets/logo-enzo.png" alt="Enzo Amadei" className="footer-logo" /><p className="footer-role">LIFE COACH &amp;<br />CONFERENCISTA</p><p>PERSONAS MÁS LIBRES<br />UN MUNDO MÁS HUMANO</p></div><div className="footer-motto"><span className="footer-accent" aria-hidden="true" />“Solo tú puedes<br /><em>cambiar tu mundo</em>”</div><div className="footer-social-col"><p className="eyebrow light">SÍGUEME EN<br />MIS REDES</p><div className="socials"><a href="https://www.facebook.com/enzo.amadei.52" target="_blank" rel="noreferrer" aria-label="Facebook"><SocialIcon name="facebook" /></a><a href="https://www.instagram.com/enzo_amadei/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="instagram" /></a><a href="https://wa.me/56966670005" target="_blank" rel="noreferrer" aria-label="WhatsApp"><SocialIcon name="whatsapp" /></a></div><p className="footer-links-label">INSPIRA <i /> TRANSFORMA <i /> LIBÉRATE</p></div></div><div className="footer-bottom"><span>© 2024 Enzo Amadei. Todos los derechos reservados.</span><span>Inicio　|　Acerca de mí　|　Programas　|　Contacto</span></div></footer>
  </main>;
}
function Stat({ icon, label, sub }: { icon: string; label: string; sub: string }) { return <div className="stat"><img src={icon} alt="" /><div>{label}<strong>{sub}</strong></div></div>; }
function Mini({ icon, text }: { icon: string; text: string }) { return <div className="mini"><img src={icon} alt="" /><span>{text}</span></div>; }
function SocialIcon({ name }: { name: "facebook" | "instagram" | "whatsapp" | "mail" }) {
  if (name === "facebook") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 1.9-5 5v3H6v4h3v4h4v-4h3l1-4h-4V9c0-.7.3-1 1-1Z" /></svg>;
  if (name === "instagram") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="4" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="1" className="social-dot" /></svg>;
  if (name === "whatsapp") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.5a8.5 8.5 0 0 0-7.2 13l-1 4 4-1A8.5 8.5 0 1 0 12 3.5Z" /><path d="M8.8 8.5c.2-.4.4-.4.7-.4h.5c.2 0 .4.1.5.4l.7 1.7c.1.2.1.4-.1.6l-.6.7c.5 1 1.3 1.7 2.4 2.2l.7-.7c.2-.2.4-.2.6-.1l1.6.8c.3.1.4.3.3.6-.2.8-.9 1.4-1.7 1.4-2 0-5.9-3.1-5.9-5.9 0-.5.1-.9.3-1.3Z" /></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></svg>;
}
